version: "3"

services:
  simnode0:
    container_name: simnode0
    image: "cosmossdk/simnode"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
    volumes:
      - ./build/simnode0/:/opt/build/simapp_home/
    command: bash ${COMMAND}.sh simnode0
    environment:
      - TZ=Asia/Bangkok
    networks:
      localnet_simnode:
        ipv4_address: 10.10.0.2

  simnode1:
    container_name: simnode1
    image: "cosmossdk/simnode"
    ports:
      - "26659-26660:26656-26657"
    volumes:
      - ./build/simnode1/:/opt/build/simapp_home/
    command: bash ${COMMAND}.sh simnode1
    environment:
      - TZ=Asia/Soul
    networks:
      localnet_simnode:
        ipv4_address: 10.10.0.3

  simnode2:
    container_name: simnode2
    image: "cosmossdk/simnode"
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build/simnode2/:/opt/build/simapp_home/
    command: bash ${COMMAND}.sh simnode2
    environment:
      - TZ=America/New_York
    networks:
      localnet_simnode:
        ipv4_address: 10.10.0.4

  simnode3:
    container_name: simnode3
    image: "cosmossdk/simnode"
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build/simnode3/:/opt/build/simapp_home/
    command: bash ${COMMAND}.sh simnode3
    environment:
      - TZ=Europe/London
    networks:
      localnet_simnode:
        ipv4_address: 10.10.0.5

networks:
  localnet_simnode:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/16
